name: CI

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.REGISTRY }}
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Build and push backend
        run: |
          docker build -t ${{ secrets.REGISTRY }}/news-backend:${{ github.sha }} ./backend
          docker push ${{ secrets.REGISTRY }}/news-backend:${{ github.sha }}
      - name: Build and push frontend
        run: |
          docker build -t ${{ secrets.REGISTRY }}/news-frontend:${{ github.sha }} ./frontend
          docker push ${{ secrets.REGISTRY }}/news-frontend:${{ github.sha }}
      - name: Deploy to cluster
        run: |
          echo "Deploy step: update k8s manifests or use helm; left as implementation detail."
